### ISSUE TITLE
Scan to http [:] unir [.] net 

### ISSUE THREAD

**Issue by sonirico** [sonirico/wpoke#17]
Traceback:

```Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/app/wpinfo/middleware.py", line 29, in view_handler
    return await fn(request)
  File "/app/wpinfo/views.py", line 38, in theme_detect
    result = await hand.poke(target_url)
  File "/usr/local/lib/python3.7/site-packages/wpoke/hand.py", line 85, in poke
    pokes = await self._poke(target_url)
  File "/usr/local/lib/python3.7/site-packages/wpoke/hand.py", line 71, in _poke
    result.data = await finger.run(target_url)
  File "/usr/local/lib/python3.7/site-packages/wpoke/fingers/theme/__init__.py", line 31, in run
    themes = await crawler.get_theme(target)
  File "/usr/local/lib/python3.7/site-packages/wpoke/fingers/theme/crawler.py", line 218, in get_theme
    css_content = await self.fetch_style_css(style_css_path)
  File "/usr/local/lib/python3.7/site-packages/wpoke/fingers/theme/crawler.py", line 177, in fetch_style_css
    status, css_content = await self._do_request(url, "GET")
  File "/usr/local/lib/python3.7/site-packages/wpoke/fingers/theme/crawler.py", line 163, in _do_request
    method=http_method.lower(), url=target_url, **self.request_options
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 963, in _create_direct_connection
    assert port is not None
AssertionError```

**Comment by sonirico** [comment]
track https://github.com/sonirico/wpoke/issues/18
